version: "3.1"

services:
  salt:
    build: ./salt
    environment:
      - PORT=${SALT_PORT}
    ports:
      - "${SALT_PORT}:${SALT_PORT}"
  user:
#    dns:
#      - "178.22.122.100"
#      - "185.51.200.2"
#    network_mode: "bridge"
    build: ./user
    environment:
      - PORT=${USER_PORT}
      - URI=${URI}
      - DB=${DB}
      - COLL=${COLL}
    ports:
      - "${USER_PORT}:${USER_PORT}"
  db:
    image: dockerhub.ir/mongo
    environment:
      - MONGO_INITDB_DATABASE=${DB}
      - MONGO_INITDB_ROOT_USERNAME=${USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD}
      - PUID=1000
      - PGID=1000
    ports:
      - "${DB_PORT}:${DB_PORT}"